### ISSUE TITLE
FormRequestValidation

### ISSUE THREAD

**Issue by tooy** [ArtichOtel/ArtichOtel_BACK#2]
Utiliser les FormRequest pour valider les datas [[cf doc](https://laravel.com/docs/9.x/validation#form-request-validation)](https://laravel.com/docs/9.x/validation#form-request-validation)
permet d'éviter la duplication et de centraliser le code de validation

**Comment by MalikAza** [comment]
Utilisations des `FormRequest` dans bcbfe64b37d93f6261b417b729ac200023183911 .
Cependant on ne peut pas éviter la duplication des validations par le faîtes qu'entre nos méthodes `store` & `update` il y a au moins un champ de différence : **required** => **sometimes** respectivement pour `store` puis `update`.
