### ISSUE TITLE
sanctum pour OfferController::destroy

### ISSUE THREAD

**Issue by tooy** [ArtichOtel/ArtichOtel_BACK#3]
Attention d'utiliser sancum pour authentifier et vérifier le role d'admin pour les routes critique tel que OfferController::destroy

**Comment by MalikAza** [comment]
Sanctum utiliser pour l'authentification et vérification du rôle admin pour les routes disponibles uniquement à ce dernier.
https://github.com/ArtichOtel/ArtichOtel_BACK/blob/dev/routes/api.php#L48
```php
Route::middleware(['auth:sanctum', 'ability:doAnything'])->group(function () {
    Route::apiResource('...', ...);
    [...]
}
```
